param(
    [string]$MatrixPath = "docs\control-matrix.csv",
    [string]$OutputPath = "src\Copilot\Controls\IniBuildsA320ControlCatalog.Generated.cs"
)

function Escape-CSharpString([string]$value) {
    return $value.Replace('\', '\\').Replace('"', '\"')
}

$rows = Import-Csv -LiteralPath $MatrixPath
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("// <auto-generated />")
$lines.Add("namespace Msfs2024Ai.Copilot.Controls;")
$lines.Add("")
$lines.Add("internal static class IniBuildsA320ControlCatalog")
$lines.Add("{")
$lines.Add("    private static readonly IReadOnlyDictionary<string, AircraftControlDefinition> Controls =")
$lines.Add("        new Dictionary<string, AircraftControlDefinition>(StringComparer.OrdinalIgnoreCase)")
$lines.Add("        {")

foreach ($row in $rows | Sort-Object Preset) {
    $preset = Escape-CSharpString $row.Preset
    $category = Escape-CSharpString $row.Category
    $code = Escape-CSharpString $row.CalculatorCode
    $source = Escape-CSharpString $row.Source
    $lines.Add(
        "            [`"$preset`"] = new AircraftControlDefinition(`"$category`", `"$preset`", `"$code`", `"$source`"),")
}

$lines.Add("        };")
$lines.Add("")
$lines.Add("    public static bool TryGet(string preset, out AircraftControlDefinition control) =>")
$lines.Add("        Controls.TryGetValue(preset, out control!);")
$lines.Add("")
$lines.Add("    public static AircraftControlDefinition GetRequired(string preset)")
$lines.Add("    {")
$lines.Add("        if (!TryGet(preset, out var control))")
$lines.Add("        {")
$lines.Add('            throw new InvalidOperationException($"Documented iniBuilds A320 preset not found: {preset}");')
$lines.Add("        }")
$lines.Add("")
$lines.Add("        return control;")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    public static int Count => Controls.Count;")
$lines.Add("}")

[System.IO.File]::WriteAllLines(
    (Join-Path (Get-Location) $OutputPath),
    $lines,
    [System.Text.UTF8Encoding]::new($false))

Write-Output "Generated $($rows.Count) controls in $OutputPath"
